export const CONTENT_ERROR_CODES = [
  'CONTENT_BODY_UNSAFE',
  'CONTENT_CATEGORY_INVALID',
  'CONTENT_CATEGORY_REQUIREMENT',
  'CONTENT_COMPANION_DUPLICATE',
  'CONTENT_COMPANION_MISSING',
  'CONTENT_COMPANION_ORPHAN',
  'CONTENT_DATE_INVALID',
  'CONTENT_DOCUMENTATION_DRIFT',
  'CONTENT_DOCUMENTATION_MISSING',
  'CONTENT_EVIDENCE_DUPLICATE',
  'CONTENT_EVIDENCE_REFERENCE',
  'CONTENT_EVIDENCE_UNSUPPORTED',
  'CONTENT_FILENAME_MISMATCH',
  'CONTENT_FIXTURE_IMPORTED',
  'CONTENT_FIXTURE_COUNT',
  'CONTENT_FIXTURE_PUBLIC',
  'CONTENT_FRONTMATTER_DUPLICATE',
  'CONTENT_FRONTMATTER_INVALID',
  'CONTENT_FRONTMATTER_NESTED',
  'CONTENT_FRONTMATTER_UNKNOWN',
  'CONTENT_LIFECYCLE_INVALID',
  'CONTENT_LIMITATION_STATUS_MISSING',
  'CONTENT_MANIFEST_DRIFT',
  'CONTENT_MEDIA_ALT_MISSING',
  'CONTENT_MEDIA_DUPLICATE',
  'CONTENT_MEDIA_SOURCE_MISSING',
  'CONTENT_MEDIA_TRANSCRIPT_MISSING',
  'CONTENT_METRIC_INCOMPLETE',
  'CONTENT_NAVIGATION_INVALID',
  'CONTENT_ORDER_DUPLICATE',
  'CONTENT_PRIVATE_PATH',
  'CONTENT_PROFILE_INVALID',
  'CONTENT_PRODUCTION_NOT_EMPTY',
  'CONTENT_PUBLICATION_INELIGIBLE',
  'CONTENT_REFERENCE_INVALID',
  'CONTENT_RELATION_DIRECTION',
  'CONTENT_RELATION_DUPLICATE',
  'CONTENT_RELATION_ORPHAN',
  'CONTENT_RELATION_SELF',
  'CONTENT_RIGHTS_UNKNOWN',
  'CONTENT_SCHEMA_INVALID',
  'CONTENT_SLUG_INVALID',
  'CONTENT_SORT_NONDETERMINISTIC',
  'CONTENT_UNSAFE_URL',
  'CONTENT_VISIBILITY_INVALID',
] as const;

export type ContentErrorCode = (typeof CONTENT_ERROR_CODES)[number];

export class ContentModelError extends Error {
  readonly code: ContentErrorCode;
  readonly context: string | undefined;

  constructor(code: ContentErrorCode, message: string, context?: string) {
    super(message);
    this.name = 'ContentModelError';
    this.code = code;
    this.context = context;
  }
}

export const contentError = (
  code: ContentErrorCode,
  message: string,
  context?: string,
): never => {
  throw new ContentModelError(code, message, context);
};
