import { spawnSync } from 'node:child_process';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import {
  countBy,
  cssValue,
  generatedDirectory,
  loadTokenSources,
  readJson,
  repositoryRoot,
  sha256,
  sourceDirectory,
  stableJson,
} from './token-utils.mjs';

const generatorVersion = '1.0.0';
const generatorPath = join(repositoryRoot, 'scripts/generate-tokens.mjs');

for (const guard of [
  'validate-token-source.mjs',
  'validate-token-references.mjs',
  'validate-token-usage.mjs',
]) {
  const result = spawnSync(process.execPath, [join(repositoryRoot, 'scripts', guard)], {
    cwd: repositoryRoot,
    encoding: 'utf8',
  });
  if (result.status !== 0) {
    if (result.stdout) process.stdout.write(result.stdout);
    if (result.stderr) process.stderr.write(result.stderr);
    throw new Error(`Token generation stopped by ${guard}.`);
  }
}

const generatorHash = sha256(await readFile(generatorPath));
const sourceManifestBytes = await readFile(join(sourceDirectory, 'source-manifest.json'));
const sourceManifest = JSON.parse(sourceManifestBytes);
const sourceManifestHash = sha256(sourceManifestBytes);
const contrastContract = await readJson(join(sourceDirectory, 'contrast-pairs.json'));
const { entries } = await loadTokenSources();

const sorted = [...entries].sort((a, b) =>
  `${a.layer}:${a.mode ?? ''}:${a.group}:${a.name}`.localeCompare(`${b.layer}:${b.mode ?? ''}:${b.group}:${b.name}`),
);

function declarations(items, indent = '    ') {
  return items
    .slice()
    .sort((a, b) => a.name.localeCompare(b.name))
    .map((entry) => `${indent}${entry.name}: ${cssValue(entry.value)};`)
    .join('\n');
}

function block(selector, items, indent = '  ') {
  return `${indent}${selector} {\n${declarations(items, `${indent}  `)}\n${indent}}`;
}

const primitive = sorted.filter((entry) => entry.layer === 'primitive');
const sharedSemantic = sorted.filter((entry) => entry.layer === 'semantic' && !entry.mode);
const dark = sorted.filter((entry) => entry.layer === 'semantic' && entry.mode === 'dark');
const light = sorted.filter((entry) => entry.layer === 'semantic' && entry.mode === 'light');
const portfolio = sorted.filter((entry) => entry.layer === 'portfolio');
const worldEntries = sorted.filter((entry) => entry.layer === 'world');
const worldSlugs = ['software', 'visual-system', 'art', 'technical-system', 'limited-media'];

function worldBlock(slug) {
  const prefix = `--azw-world-${slug}-`;
  const definitions = worldEntries.filter((entry) => entry.group === `world.${slug}`);
  const aliases = definitions.map((entry) => ({
    ...entry,
    name: `--azw-world-${entry.name.slice(prefix.length)}`,
    value: `{${entry.name}}`,
  }));
  return `${block(`[data-world="${slug}"]`, definitions)}\n\n${block(`[data-world="${slug}"]`, aliases)}`;
}

const defaultWorldDefinitions = worldEntries.filter((entry) => entry.group === 'world.software');
const defaultWorldAliases = defaultWorldDefinitions.map((entry) => ({
  ...entry,
  name: `--azw-world-${entry.name.slice('--azw-world-software-'.length)}`,
  value: `{${entry.name}}`,
}));

const metadataHeader = `/* Generated by scripts/generate-tokens.mjs v${generatorVersion}.\n * Source manifest SHA-256: ${sourceManifestHash}\n * Generator SHA-256: ${generatorHash}\n * DO NOT EDIT: update src/tokens/source and regenerate.\n */`;

const css = `${metadataHeader}
@layer azw.tokens.primitives, azw.tokens.semantic, azw.tokens.aliases, azw.tokens.worlds;

@layer azw.tokens.primitives {
${block(':root', primitive)}
}

@layer azw.tokens.semantic {
${block(':root', sharedSemantic)}

  :root {
    color-scheme: dark light;
  }

${block(':root, :root[data-theme="dark"]', dark)}

  :root[data-theme="dark"] {
    color-scheme: dark;
  }

${block(':root[data-theme="light"]', light)}

  :root[data-theme="light"] {
    color-scheme: light;
  }

  @media (prefers-color-scheme: light) {
${block(':root:not([data-theme])', light, '    ')}

    :root:not([data-theme]) {
      color-scheme: light;
    }
  }

  @media (prefers-reduced-motion: reduce) {
    :root {
      --azw-motion-duration-micro: var(--azw-motion-duration-reduced);
      --azw-motion-duration-route: var(--azw-motion-duration-reduced);
      --azw-motion-duration-navigation: var(--azw-motion-duration-reduced);
      --azw-mark-motion-allowance: var(--azw-mark-reduced-motion);
    }
  }

  @media (prefers-contrast: more) {
    :root {
      --azw-color-border-default: var(--azw-color-border-strong);
      --azw-color-divider: var(--azw-color-border-strong);
    }
  }

  @media print {
${block(':root, :root[data-theme]', light, '    ')}

    :root,
    :root[data-theme] {
      color-scheme: light;
    }
  }

  @media (forced-colors: active) {
    :root {
      --azw-color-canvas: Canvas;
      --azw-color-surface-primary: Canvas;
      --azw-color-surface-alternate: Canvas;
      --azw-color-surface-raised: Canvas;
      --azw-color-surface-inset: Canvas;
      --azw-color-surface-code: Canvas;
      --azw-color-surface-art-neutral: Canvas;
      --azw-color-text-primary: CanvasText;
      --azw-color-text-secondary: CanvasText;
      --azw-color-text-muted: CanvasText;
      --azw-color-text-faint: GrayText;
      --azw-color-link-default: LinkText;
      --azw-color-link-hover: LinkText;
      --azw-color-link-active: ActiveText;
      --azw-color-link-visited: VisitedText;
      --azw-color-border-default: CanvasText;
      --azw-color-border-strong: CanvasText;
      --azw-focus-ring: Highlight;
      --azw-focus-ring-offset: Canvas;
      --azw-color-selection-background: Highlight;
      --azw-color-selection-text: HighlightText;
      --azw-mark-forced-colors-display: none;
    }
  }
}

@layer azw.tokens.aliases {
${block(':root', portfolio)}
}

@layer azw.tokens.worlds {
${block(':root', defaultWorldDefinitions)}

${block(':root', defaultWorldAliases)}

${worldSlugs.map(worldBlock).join('\n\n')}
}
`;

const genericWorldNames = defaultWorldAliases.map((entry) => entry.name);
const uniqueNames = [...new Set([...entries.map((entry) => entry.name), ...genericWorldNames])].sort();
const themeModes = ['system', 'dark', 'light'];

const namesTs = `${metadataHeader.replaceAll('/*', '//').replaceAll(' *', '//').replaceAll(' */', '//')}
export const tokenNames = ${JSON.stringify(uniqueNames, null, 2)} as const;

export type TokenName = (typeof tokenNames)[number];
`;

const tokenMetadata = sorted.map(({ name, layer, domain, mode, group, type, classification, description }) => ({
  name,
  layer,
  domain,
  ...(mode ? { mode } : {}),
  group,
  type,
  classification,
  description,
}));

const tokensTs = `${metadataHeader.replaceAll('/*', '//').replaceAll(' *', '//').replaceAll(' */', '//')}
export const themeModes = ${JSON.stringify(themeModes)} as const;
export type ThemeMode = (typeof themeModes)[number];

export const projectWorlds = ${JSON.stringify(worldSlugs)} as const;
export type ProjectWorld = (typeof projectWorlds)[number];

export const tokenMetadata = ${JSON.stringify(tokenMetadata, null, 2)} as const;

export const generatedMetadata = ${JSON.stringify({
  implementation: sourceManifest.implementationName,
  implementationVersion: sourceManifest.implementationVersion,
  generatorVersion,
  sourceManifestSha256: sourceManifestHash,
  generatorSha256: generatorHash,
}, null, 2)} as const;
`;

const outputDrafts = {
  'tokens.css': css,
  'token-names.ts': namesTs,
  'tokens.ts': tokensTs,
};

const generatedFileHashes = Object.fromEntries(
  Object.entries(outputDrafts).map(([name, content]) => [name, sha256(content)]).sort(([a], [b]) => a.localeCompare(b)),
);

const manifest = {
  schemaVersion: '1.0.0',
  implementation: sourceManifest.implementationName,
  implementationVersion: sourceManifest.implementationVersion,
  generatorVersion,
  generatorSha256: generatorHash,
  sourceManifestSha256: sourceManifestHash,
  acceptedDocumentHashes: sourceManifest.documentHashes,
  tokenCount: entries.length,
  uniqueTokenNameCount: uniqueNames.length,
  tokenCountByLayer: countBy(entries, 'layer'),
  tokenCountByDomain: countBy(entries, 'domain'),
  themeModes,
  projectWorlds: worldSlugs,
  themeMappingCount: dark.length + light.length,
  contrastPairCount: contrastContract.pairs.length,
  generatedFileHashes,
  timestampPolicy: 'No generated timestamp; identical sources and generator produce identical bytes.',
};

const outputs = {
  ...outputDrafts,
  'token-manifest.json': stableJson(manifest),
};

if (process.argv.includes('--check')) {
  const mismatches = [];
  for (const [name, expected] of Object.entries(outputs)) {
    let actual;
    try {
      actual = await readFile(join(generatedDirectory, name), 'utf8');
    } catch {
      mismatches.push(`${name} is missing`);
      continue;
    }
    if (actual !== expected) mismatches.push(`${name} differs from deterministic output`);
  }
  if (mismatches.length > 0) {
    for (const mismatch of mismatches) console.error(`- ${mismatch}`);
    process.exitCode = 1;
  } else {
    console.log(`Generated token check passed: ${Object.keys(outputs).length} files are current.`);
  }
} else {
  await mkdir(generatedDirectory, { recursive: true });
  for (const [name, content] of Object.entries(outputs)) {
    await writeFile(join(generatedDirectory, name), content);
  }
  console.log(`Generated ${Object.keys(outputs).length} token files from ${entries.length} scoped declarations.`);
}
